<?php
	$gid = $_REQUEST['gid'];

	if ($gid == '2') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"DesktopArmada","gtype":"mp","dmode":"","mplayers":"2","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":463857,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"DesktopArmada","menu":"instructions","wv":473702,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"cc25db750bed4b13","splash":"/2/desktoparmadabg","game":"/2/desktoparmada","stingerv":0,"devv":0,"splashv":1,"gamev":"26"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '3') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"BuggleConnect","gtype":"mp","dmode":"","mplayers":"4","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":478256,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"BuggleConnect","menu":"","wv":689735,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"01d9cb18f014cda2","splash":"/3/buggleconnectbg","game":"/3/buggleconnect","stingerv":0,"devv":0,"splashv":1,"gamev":"16"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '7') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"FlashElementTD2","gtype":"sp","dmode":"","mplayers":"6","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":850436,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"","menu":"","wv":713163,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"9b9509ad5e78bb5e","splash":"/7/flashelementtd2bg","game":"/7/flashelementtd2","stingerv":0,"devv":0,"splashv":1,"gamev":"9"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '8') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"AttackoftheBuggles","gtype":"sp","dmode":"","mplayers":"6","friends":"","pd":"","awards":"","stats":"special:0,slow:0,worth:3,buggles:6,consumed:5","ls":"","host":"storage.cloud.casualcollective.com","seed":184960,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"","menu":"","wv":406933,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"56c5e41b7edd8f08","splash":"/8/attackofthebugglesbg","game":"/8/attackofthebuggles","stingerv":0,"devv":0,"splashv":1,"gamev":"14"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '9') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"BuggleStars","gtype":"sp","dmode":"","mplayers":"6","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":95460,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"","menu":"","wv":227313,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"66e4d3a851a5eaf6","splash":"/9/bugglestarsbg","game":"/9/bugglestars","stingerv":0,"devv":0,"splashv":1,"gamev":"24"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '10') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"TheSpaceGame","gtype":"sp","dmode":"","mplayers":"0","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":886433,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"","menu":"","wv":33928,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"8b88fbe9eb9f092f","splash":"/10/thespacegamebg","game":"/10/thespacegame","stingerv":0,"devv":0,"splashv":1,"gamev":"83"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '100') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"TheSpaceGame","gtype":"sp","dmode":"","mplayers":"0","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":886433,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"","menu":"","wv":33928,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"8b88fbe9eb9f092f","splash":"/100/thespacegamebg","game":"/100/thespacegame","stingerv":0,"devv":0,"splashv":1,"gamev":"83"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '13') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"DesktopTDPro","gtype":"mp","dmode":"","mplayers":"6","friends":"","pd":"","awards":"","stats":"","ls":"","host":"https://chat.kongregate.com/gamez/0004/4150/live/desktoptdpro.swf?kongregate_game_version=1240857298","seed":358205,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"DesktopTDPro","menu":"","wv":14397,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"f67e8e853c02f174","splash":"/13/desktoptdprobg","game":"/13/desktoptdpro","stingerv":0,"devv":0,"splashv":1,"gamev":"35"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	} else if ($gid == '16') {
		echo '{"result":1,"pid":"-1","pname":"","gname":"TSGMissions","gtype":"sp","dmode":"","mplayers":"1","friends":"","pd":"","awards":"","stats":"","ls":"","host":"storage.cloud.casualcollective.com","seed":172389,"port":9339,"server":"174.129.0.37","lobby":"lobby","zone":"pub","ext":"","menu":"","wv":334086,"r":0,"pms":"0","lr":"cc","swfs":{"base":"http://storage.cloud.casualcollective.com/zones/pub","stinger":"/stingers/ccblocks.swf","dev":"","ad":"/ads/mochiad","adid":"","splash":"/16/tsgmissionsbg","game":"/16/tsgmissions","stingerv":0,"devv":0,"splashv":1,"gamev":"16"},"as":"http://storage.casualcollective.com/avatars","netcode":"1","urr":0,"ss":"http://sessions.casualcollective.com"}';
	}